name: CI MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TRAIN_CSV: "preprocessed-dataset/x_train_preprocessing.csv"
  VALID_CSV: "preprocessed-dataset/x_valid_preprocessing.csv"
  TARGET_VAR: "Egg Sales"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Start CI/CD pipeline"

      - uses: actions/checkout@v3
        with:
          lfs: true  # ✅ Penting untuk LFS support

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo "Train CSV: $TRAIN_CSV"
          echo "Valid CSV: $VALID_CSV"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow tensorflow pandas numpy keras_tuner matplotlib scikit-learn

      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local 
          
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Set up Git auth with PAT
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs track "mlruns/**"
          git add .gitattributes || true
          git commit -m "Track large files in mlruns with Git LFS" || true
          git push origin main || true  # push .gitattributes kalau belum ada

      - name: Save mlruns to repo
        run: |
          git add -f mlruns/
          git commit -m "Save mlruns from CI run" || true
          git push origin main || true

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "penjualan_telur_model"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag penjualan_telur_model ${{ secrets.DOCKER_HUB_USERNAME }}/penjualan_telur_model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/penjualan_telur_model:latest

      - name: Complete job
        run: echo "✅ CI/CD workflow selesai dan model disimpan ke repo"
