name: CI MLflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CSV_URL: "MLproject/train_pca.csv"
  TARGET_VAR: "Credit_Score"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check environment variables
        run: echo "Dataset URL is $CSV_URL"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Run MLflow project
        run: |
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Copy model artifacts to saved_models/
        run: |
          mkdir -p saved_models/$RUN_ID
          cp -r mlruns/0/$RUN_ID/artifacts/model/* saved_models/$RUN_ID/

      - name: Commit and push model artifacts
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add saved_models/
          git commit -m "Add model artifacts for run_id $RUN_ID"
          git push origin main

      - name: Build Docker model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
