name: CI MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TRAIN_CSV: "preprocessed-dataset/x_train_preprocessing.csv"
  VALID_CSV: "preprocessed-dataset/x_valid_preprocessing.csv"
  TARGET_VAR: "Egg Sales"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Start CI/CD pipeline"

      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo "Train CSV: $TRAIN_CSV"
          echo "Valid CSV: $VALID_CSV"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow tensorflow pandas numpy keras_tuner matplotlib scikit-learn dagshub

      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local 
          
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Copy artifacts to repo folder
        run: |
          mkdir -p saved_artifacts/
          cp -r mlruns/0/$RUN_ID/artifacts/model/* saved_artifacts/
          echo "Artifacts copied to saved_artifacts/"

      - name: Commit artifacts to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add saved_artifacts/
          git commit -m "🔁 Add trained model artifacts [skip ci]" || echo "No changes to commit"
          git push origin main

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "penjualan_telur_model"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag penjualan_telur_model ${{ secrets.DOCKER_HUB_USERNAME }}/penjualan_telur_model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/penjualan_telur_model:latest

      - name: Complete job
        run: echo "✅ CI/CD workflow selesai dan model disimpan ke repo"
